version: '3'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Expose the frontend on port 3000
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Expose the backend on port 5000
    environment:
      NODE_ENV: production
      MONGO_URL: mongodb://mongo:27017/yolomy # MongoDB connection URL
    depends_on:
      - mongo
    # volumes:
    #   - ./backend:/app # Map backend code for development

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017" # Expose MongoDB on default port
    volumes:
      - mongo-data:/data/db # Persist MongoDB data

volumes:
  mongo-data:
