#will setup all guests for common dependencies & processes
- hosts: all
  become: true
  roles:
    - admin_server_provisioner

#will setup backend service
- hosts: backendserver
  roles:
    - backend_service_provisioner
    - frontend_service_provisioner

#will setup frontend service  
- hosts: frontendserver 
  roles:
    - frontend_service_provisioner
