#will setup all guests for common dependencies & processes
- hosts: all
  become: true
  
  roles:
    - admin_server_provisioner

#will setup backend service
- hosts: backendserver
  roles:
    - backend_server_provisioner
 

#will setup frontend service  
- hosts: frontendserver 
  roles:
    - frontend_server_provisioner
