---
# tasks file for admin_server_provisioner
- name: Update system 
  apt:
    update_cache: true

- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present

- name: Add Docker’s official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Set up the stable repository for Docker
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    state: present

- name: Install Docker
  apt:
    name: docker-ce
    state: present


- name: Ensure CLI plugins directory exists
  file:
    path: "/usr/local/lib/docker/cli-plugins"
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Download Docker Compose binary for Linux x86_64
  get_url:
    url: "https://github.com/docker/compose/releases/download/v2.29.7/docker-compose-darwin-x86_64"
    dest: "/usr/local/lib/docker/cli-plugins/docker-compose"
    mode: 'u+x'

- name: Ensure Docker Compose binary is executable
  file:
    path: "/usr/local/lib/docker/cli-plugins/docker-compose"
    mode: '0755'
    owner: root
    group: root


- name: Add user to the docker group
  user:
    name: "{{ vagrant_user }}"  
    group: "{{ docker_user }}"
    append: yes

- name: Restart Docker service
  service:
    name: docker
    state: restarted