---
# tasks file for frontend_server_provisioner
- name: Navigate to the project directory and build the Docker image
  command: docker build -t frontend_image .
  become: true
  args:
    chdir: /home/vagrant/yolo/client

- name: Run the Docker container
  become: true
  docker_container:
    name: frontend_container
    image: frontend_image
    state: started
    restart_policy: always
    ports:
      - "3000:3000"
